arm:
  # kinematics_solver_search_resolution: 0.0050000000000000001
  # kinematics_solver_timeout: 3.0 #0.0050000000000000001
  # position_only_ik: False # compute position and orienation of the gripper

  # kinematics_solver: pick_ik/PickIkPlugin
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_search_resolution: 0.0050000000000000001
  # kinematics_solver_timeout: 0.5 #0.0050000000000000001
  # position_only_ik: True # compute position and orienation of the gripper

  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 3.0
  kinematics_solver_attempts: 50
  mode: global
  position_scale: 1.0
  rotation_scale: 0.1
  position_threshold: 10.0
  orientation_threshold: 10.0
  cost_threshold: 100000.0
  minimal_displacement_weight: 0.0
  stop_optimization_on_valid_solution: False
  # gd_step_size: 0.0001